### ISSUE TITLE
Multi-select support for "Send to Catagory"

### ISSUE THREAD

**Issue by UlrikHD** [Frodo45127/runcher#2]
Currently when selecting multiple items, right clicking and using "Send to Category" does nothing. A more expected behaviour would be to send all selected items to the new category.

**Comment by Frodo45127** [comment]
That's because the code to properly know what you have selected and enable/disable options in the context menu is not yet implemented, so I had to limit it to single selections to avoid weird behavior. So, it's coming at some point.

**Comment by Frodo45127** [comment]
Done for 0.1.1.

**Comment by LyciaPintella** [comment]
This is literally saving me hours finding a crashy mod. Thanks!
