### ISSUE TITLE
Does not load mods for Empire Total War

### ISSUE THREAD

**Issue by Lord-Calvariam** [Frodo45127/runcher#8]
**Describe your problem**
What the title says but I think I know why it doesn't work.
Checking the scripts folder, Runcher creates a file called user.script.txt
I think that is the correct name for later games but for empire the name of the file needs to be user.empire_script.txt

**Comment by Frodo45127** [comment]
mmm that's weird. When I tested it with the AUM mod it worked. What mod were you trying to load?

**Comment by Lord-Calvariam** [comment]
There were three mods I was trying to load.

Blood and Smoke (Full version) = https://www.twcenter.net/forums/showthread.php?237457-Smoke-and-Blood-Mod-Thread-(Last-Update-28-02-10-Blood-Mod-for-NTW-)-)

Combined sound by sgt_melin = https://www.twcenter.net/forums/showthread.php?253279-Sgt_melins-Combine-soundmod-v3-and-a-darthversion-now(28-12-09)

Third one is a mod I made that removes projectile trails = https://www.mediafire.com/file/q5bs4uqultjyzmc/no_trails.pack/file

**Comment by Frodo45127** [comment]
Ok, I'm not sure why it worked last time, but indeed I just tested it and it doesn't even load aum. Changing the name of the userscript works, so I've changed it so when using Runcher to launch Empire, it uses the correct user script file. Probably will make a bugfix release this week with this fix. Thanks for the report.
